services:
    bot:
        build: .
        restart: always
        stop_signal: SIGINT
        ports:
            - "127.0.0.1:8777:8777"
        networks:
            - remnawave-network
            - default
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            SHOP_NAME: ${SHOP_NAME}
            PERIOD_LIMIT: ${PERIOD_LIMIT}
            SUPPORT_LINK: ${SUPPORT_LINK}
            YOOKASSA_TOKEN: ${YOOKASSA_TOKEN}
            YOOKASSA_SHOPID: ${YOOKASSA_SHOPID}
            EMAIL: ${EMAIL}
            CRYPTO_TOKEN: ${CRYPTO_TOKEN}
            MERCHANT_UUID: ${MERCHANT_UUID}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_ADDRESS: ${DB_ADDRESS}
            DB_PORT: ${DB_PORT}
            PANEL_HOST: ${PANEL_HOST}
            WEBHOOK_URL: ${WEBHOOK_URL}
            WEBHOOK_PORT: ${WEBHOOK_PORT}
            WEBHOOK_SECRET: ${WEBHOOK_SECRET}
            TG_INFO_CHANEL: ${TG_INFO_CHANEL}
            STARS_PAYMENT_ENABLED: ${STARS_PAYMENT_ENABLED}
            CRYPTO_PAYMENT_ENABLED: ${CRYPTO_PAYMENT_ENABLED}
            ADMINS: ${ADMINS}
            VPN_NOT_WORKING_LINK: ${VPN_NOT_WORKING_LINK}
            REMNAWAVE_TOKEN: ${REMNAWAVE_TOKEN}
        volumes:
            - "./goods.json:/app/goods.json"
            - "./locales:/app/locales"
        depends_on:
            db:
                condition: service_healthy
    db:
        image: mariadb:lts
        restart: always
        ports:
          - "127.0.0.1:3306:3306"
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
            MARIADB_DATABASE: ${DB_NAME}
            MARIADB_USER: ${DB_USER}
            MARIADB_PASSWORD: ${DB_PASS}
        volumes:
            - "mysql-data:/var/lib/mysql"
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            start_period: 10s
            start_interval: 3s
            interval: 10s
            timeout: 5s
            retries: 3
        networks:
            - default
networks:
  remnawave-network:
    name: remnawave-network
    external: true
  default:
    driver: bridge
volumes:
  mysql-data:
